name: Deploy Book Project (CD Pipeline)

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup SSH and deploy
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script: |
                      sudo apt update && sudo apt upgrade -y
                      if [ ! -d "projects" ]; then
                          mkdir -p projects
                      fi
                      cd projects
                      if [ ! -d "fastapi-book-project" ]; then
                          git clone https://github.com/KING-REX/fastapi-book-project.git
                      else
                          git pull origin main
                      fi
                      cd fastapi-book-project
                      python3 -m venv venv
                      source venv/bin/activate
                      pip install --upgrade pip
                      pip install -r requirements.txt

                      if [ ! -f "/etc/systemd/system/fastapi-book-project.service" ]; then
                          sudo tee /etc/systemd/system/fastapi-book-project.service << EOF
                          [Unit]
                          Description=FastAPI Book Project
                          After=network.target

                          [Service]
                          User=hng_rex
                          WorkingDirectory=/home/hng_rex/projects/fastapi-book-project
                          Environment="PATH=/home/hng_rex/projects/fastapi-book-project/venv/bin"
                          ExecStart=/home/hng_rex/projects/fastapi-book-project/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000
                          Restart=always

                          [Install]
                          WantedBy=multi-user.target
                          EOF
                      fi

                      # Reload systemd, enable and restart the service
                      sudo systemctl daemon-reload
                      sudo systemctl enable fastapi-book-project
                      sudo systemctl restart fastapi-book-project            

                      # Restart nginx
                      sudo nginx -t 
                      sudo systemctl restart nginx
